"""ingredients table

Revision ID: 1ecacd58e13f
Revises: 4bda583b653e
Create Date: 2019-10-06 22:51:27.957214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecacd58e13f'
down_revision = '4bda583b653e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('measurement', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_recipe_timestamp'), 'recipe', ['timestamp'], unique=False)
    op.drop_index('ix_recipe_description', table_name='recipe')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recipe_description', 'recipe', ['description'], unique=False)
    op.drop_index(op.f('ix_recipe_timestamp'), table_name='recipe')
    op.drop_column('recipe', 'timestamp')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
